name: auction_repository
description: A repository that handles auction related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  network_api:
    path: ../network_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.21.4
