name: authentication_repository
description: A repository that handles vehicle_auction related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  network_api:
    path: ../network_api
  secure_storage_repository:
    path: ../secure_storage_repository
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.21.4
